services:
  app:
    image: agents-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agents-service-app
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge